@startuml ER

entity "employees" as employees {
  +-- ID (PK) : INT(11)
  +-- store_id (PK) : INT(11)
  --
  name : CHAR(50)
  number (UNI) : INT(11)
  password (UNI) : BIGINT(20)
  is_manager : BOOLEAN
}

' entity "managers" as managers {
'   +-- ID (PK) : INT(11)
'   --
'   name : CHAR(50)
'   number (UNI) : INT(11)
'   password (UNI) : BIGINT(20)
' }

entity "shift_time" as shift_time {
  +-- ID (PK) : INT(11)
  +-- shift_date_id (FK) : INT(11)
  --
  start_time : TIME
  end_time : TIME
}

entity "shift_date" as shift_date {
  +-- ID (PK) : INT(11)
  --
  work_day : DATE
  is_attendance : BOOLEAN
}

entity "employer_shifts" as employer_shifts {
  +-- ID (PK) : INT(11)
  +-- employer_id (FK) : INT(11)
  +-- shift_date_id (FK) : INT(11)
}

entity "approve_month" as approve_month {
  +-- ID (PK) : INT(11)
  --
  is_approve : BOOLEAN
}

entity "departments" as departments {
  +-- ID (PK) : INT(11)
  +-- employer_id (FK) : INT(11)
  --
  name : CHAR(50)
}

entity "skills" as skills {
  +-- ID (PK) : INT(11)
  --
  name : CHAR(50)
  is_processing : BOOLEAN
}

entity "employer_skills" as employer_skills {
  +-- ID (PK) : INT(11)
  +-- employer_id (FK) : INT(11)
  +-- skill_id (FK) : INT(11)
}

entity "stores" as stores {
  +-- ID (PK) : INT(11)
  --
  name : CHAR(50)
  number : INT(5)
  password (UNI) : INT(11)
}

entity "information" as information {
  +-- ID (PK) : INT(11)
  +-- store_id (FK) : INT(11)
  --
  content : VARCHAR(255)
}
stores -r-{ information
stores -d-{ employees
employees -l-{ employer_shifts
employer_shifts }-u- shift_date
shift_time --{ shift_date
employer_skills -l-{ employees
employer_skills --{ skills
departments -u-{ employees
approve_month -l-{ shift_time

@enduml