@startuml ER

entity "employees" as employees {
  +-- ID (PK) : INT(11)
  +-- store_id (PK) : INT(11)
  --
  name : CHAR(50)
  number (UNI) : INT(11)
  password (UNI) : CHAR(20)
  is_manager : BOOLEAN
}

entity "shift_times" as shift_times {
  +-- ID (PK) : INT(11)
  +-- shift_date_id (FK) : INT(11)
  --
  start_time : TIME
  end_time : TIME
}

entity "shift_dates" as shift_dates {
  +-- ID (PK) : INT(11)
  --
  work_day : DATE
  is_attendance : BOOLEAN
}

entity "employer_shifts" as employer_shifts {
  +-- ID (PK) : INT(11)
  +-- employer_id (FK) : INT(11)
  +-- shift_date_id (FK) : INT(11)
}

entity "approve_months" as approve_months {
  +-- ID (PK) : INT(11)
  +-- store_id (FK) : INT(11)
  --
  is_approve : BOOLEAN
}

entity "departments" as departments {
  +-- ID (PK) : INT(11)
  +-- employer_id (FK) : INT(11)
  --
  name : CHAR(50)
}

entity "skills" as skills {
  +-- ID (PK) : INT(11)
  --
  name : CHAR(50)
  is_processing : BOOLEAN
}

entity "employer_skills" as employer_skills {
  +-- ID (PK) : INT(11)
  +-- employer_id (FK) : INT(11)
  +-- skill_id (FK) : INT(11)
}

entity "stores" as stores {
  +-- ID (PK) : INT(11)
  --
  name : CHAR(50)
  number : INT(5)
  password (UNI) : CHAR(20)
}

entity "notices" as notices {
  +-- ID (PK) : INT(11)
  +-- store_id (FK) : INT(11)
  --
  content : VARCHAR(255)
}
stores -r-{ notices
stores -d-{ employees
employees -l-{ employer_shifts
employer_shifts }-u- shift_dates
shift_times --{ shift_dates
employer_skills -l-{ employees
employer_skills --{ skills
departments -u-{ employees
approve_months --{ stores

@enduml